// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/openshift/api/insights/v1alpha1"
)

// DataGatherSpecApplyConfiguration represents an declarative configuration of the DataGatherSpec type for use
// with apply.
type DataGatherSpecApplyConfiguration struct {
	DataPolicy        *v1alpha1.DataPolicy `json:"dataPolicy,omitempty"`
	DisabledGatherers []string             `json:"disabledGatherers,omitempty"`
}

// DataGatherSpecApplyConfiguration constructs an declarative configuration of the DataGatherSpec type for use with
// apply.
func DataGatherSpec() *DataGatherSpecApplyConfiguration {
	return &DataGatherSpecApplyConfiguration{}
}

// WithDataPolicy sets the DataPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataPolicy field is set to the value of the last call.
func (b *DataGatherSpecApplyConfiguration) WithDataPolicy(value v1alpha1.DataPolicy) *DataGatherSpecApplyConfiguration {
	b.DataPolicy = &value
	return b
}

// WithDisabledGatherers adds the given value to the DisabledGatherers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DisabledGatherers field.
func (b *DataGatherSpecApplyConfiguration) WithDisabledGatherers(values ...string) *DataGatherSpecApplyConfiguration {
	for i := range values {
		b.DisabledGatherers = append(b.DisabledGatherers, values[i])
	}
	return b
}
